name: ${project.artifactId}
main: ${package}.BetterChunkLoader
version: ${project.version}

commands:
   betterchunkloader:
      description: OP commands
      aliases: [bcl]

permissions:
   betterchunkloader.onlineonly:
      description: Permission to create new onlineonly chunk loaders
      default: false
   betterchunkloader.alwayson:
      description: Permission to create new alwayson chunk loaders
      default: false
   betterchunkloader.list.own:
      description: List own chunk loaders
      default: true
   betterchunkloader.unlimitedchunks:
      description: Override chunks amount limits
      default: false
   betterchunkloader.list.others:
      description: List others chunk loaders
      default: op
   betterchunkloader.edit:
      description: Edit others chunk loaders
      default: op
   betterchunkloader.adminloader:
      description: Create admin chunk loaders
      default: op
   betterchunkloader.info:
      description: Show general statistics
      default: op
   betterchunkloader.delete:
      description: Delete player chunk loaders
      default: op
   betterchunkloader.reload:
      description: Reload the plugin
      default: op
